from typing import SupportsBytes

class TrackedBuffer:
    def __new__(cls, buffer: SupportsBytes): ...

    @property
    def buffer(self) -> SupportsBytes: ...

    def _ref(self) -> None: ...
    def _deref(self) -> None: ...
