from typing import Generic, TypeVar

B = TypeVar('B')

class TrackedBuffer(Generic[B]):
    def __new__(cls, buffer: B): ...
    def __init__(self, buffer: B): ...

    @property
    def buffer(self) -> B: ...

    def _ref(self) -> None: ...
    def _deref(self) -> None: ...
